export const COURT_ALIASES: Record<string, string[]> = {
  'Birmingham Crown Court': ['birmcf', 'birmhm'],
  'Bolton Crown Court': ['bolton'],
  'Bournemouth Combined Court': ['bourne'],
  'Bradford Crown Court': ['bradfd'],
  'Bristol Crown Court': ['bristl'],
  'Burnley Crown Court': ['burnl'],
  'Cambridge Crown Court': ['cambri'],
  'Canterbury Combined Court': ['canter'],
  'Cardiff Crown Court': ['cardif'],
  'Carlisle Combined Court': ['carlil'],
  'Central Criminal Court': ['centrl'],
  'Chelmsford Crown Court': ['chelms'],
  'Chester Crown Court': ['chestr'],
  'Croydon Crown Court': ['croydn'],
  'Derby Combined Court': ['derby'],
  'Doncaster Combined Court': ['doncas'],
  'Durham Crown Court': ['durh', 'durha'],
  'Exeter Crown Court': ['exeter'],
  'Gloucester Crown Court': ['gloucs'],
  'Great Grimsby Combined Court': ['gtgrim'],
  'Guildford Crown Court': ['guildf'],
  'Harrow Crown Court': ['harrow'],
  'Kingston-upon-Hull Combined Court': ['hull'],
  'Inner London Crown Court': ['inlond'],
  'Isle of Wight Combined Court': ['iow'],
  'Isleworth Crown Court': ['islwth'],
  'Kingston-upon-Thames Crown Court': ['kingsl', 'kingut'],
  'Leeds Combined Court': ['leeds'],
  'Leicester Crown Court': ['leics'],
  'Lewes Combined Court': ['lewes'],
  'Lincoln Crown Court': ['lincln'],
  'Liverpool Crown Court': ['livr', 'livrpl'],
  'Luton Crown Court': ['luton'],
  'Maidstone Combined Court': ['maidst'],
  'Manchester Crown Court': ['mancrn'],
  'Manchester Minshull Street Crown Court': ['manmin'],
  'Merthyr Tydfil Combined Court': ['merthy'],
  'Mold Justice Centre': ['mold'],
  'Newcastle upon Tyne Crown Court': ['newcst'],
  'Newport Crown Court': ['newprt'],
  'Norwich Combined Court': ['norwch'],
  'Nottingham Crown Court': ['notts'],
  'Oxford Combined Court': ['oxford'],
  'Peterborough Combined Court': ['peterb'],
  'Plymouth Combined Court': ['plymth'],
  'Portsmouth Combined Court': ['portsm'],
  'Preston Combined Court': ['prestn'],
  'Reading Crown Court': ['readng'],
  'Salisbury Law Courts': ['salis'],
  'Sheffield Combined Court': ['sheffd'],
  'Shrewsbury Crown Court': ['shrews'],
  'Snaresbrook Crown Court': ['snares'],
  'Southampton Combined Court': ['soton'],
  'Southwark Crown Court': ['southk'],
  'Stafford Combined Court': ['staffs'],
  'St. Albans Crown Court': ['stalba'],
  'Stoke-on-Trent Combined Court': ['stoke'],
  'Swansea Crown Court': ['swanse'],
  'Swindon Combined Court': ['swindn'],
  'Taunton Combined Court': ['tauntn'],
  'Teesside Combined Court': ['teesde'],
  'Truro Combined Court': ['truro'],
  'Warwick Combined Court': ['warwic'],
  'Winchester Combined Court': ['winch'],
  'Wolverhampton Combined Court': ['wolver'],
  'Wood Green Crown Court': ['woodgn', 'wdgn'],
  'Woolwich Crown Court': ['woolch'],
  'Worcester Combined Court': ['worcs'],
  'York Crown Court': ['york'],
};
