options:
  max-warnings: 0
files:
  include: 'src/**/*.scss'
  ignore:
    - 'src/main/views/govuk/components/**'
rules:
  no-misspelled-properties:
    - 1
    - 'extra-properties':
        - 'aspect-ratio'
  no-important: 0
