nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    PRE_API_URL: https://sds-api-mgmt.staging.platform.hmcts.net/pre-api
    PORTAL_URL: https://pre-portal-staging.staging.platform.hmcts.net
