nodejs:
  applicationPort: 4550
  aadIdentityName: pre
  ingressHost: pre-portal.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'sdshmctspublic.azurecr.io/pre/portal:latest'
  keyVaults:
    pre-hmctskv:
      secrets:
        - name: redis6-access-key
          alias: REDIS_ACCESS_KEY
        - name: AppInsightsInstrumentationKey
          alias: APPINSIGHTS_INSTRUMENTATIONKEY
        - name: apim-sub-portal-primary-key
          alias: APIM_SUB_PORTAL_PRIMARY_KEY
        - name: apim-sub-portal-secondary-key
          alias: APIM_SUB_PORTAL_SECONDARY_KEY
        - name: pre-portal-sso
          alias: B2C_APP_CLIENT_SECRET
        - name: b2c-test-login-email
          alias: B2C_TEST_LOGIN_EMAIL
        - name: b2c-test-login-password
          alias: B2C_TEST_LOGIN_PASSWORD
  environment:
    REDIS_HOST: 'pre-portal-{{ .Values.global.environment }}.redis.cache.windows.net'
    PORTAL_URL: https://pre-portal.platform.hmcts.net
    ALLOW_CONFIG_MUTATIONS: true
