name: Update B2C Callback URLs
on:
  schedule:
    # Daily at 6PM Mon-Fri UTC
    - cron: '0 18 * * 1-5'
  pull_request:
    branches: ['master']

permissions:
  id-token: write
  contents: read

jobs:
  update_urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.B2C_DEV_CREDENTIALS }}
          allow-no-subscriptions: true

      - run: |
          tenant_id=${{ secrets.B2C_TENANT_ID }}
          app_id=${{ secrets.B2C_CLIENT_ID }}
          pr_ids=$(gh pr list --json number --repo $GITHUB_REPOSITORY | jq -r '.[].number')

          echo "PR IDs:/n $pr_ids"

          # https://localhost:4551/callback
          # https://pre-portal-staging.staging.platform.hmcts.net/callback
          # https://pre-portal.staging.platform.hmcts.net/callback

          for pr_number in $pr_ids
          do
          redirect_uri="https://pre-portal-pr-${pr_number}.dev.platform.hmcts.net/callback"
          az ad app update --id $app_id --web-redirect-uris $redirect_uri
          done
        env:
          REPO: ${{ github.event.repository.name }}
          GH_TOKEN: ${{ github.token }}
