name: Update B2C Callback URLs
on:
  schedule:
    # Daily at 6:30PM Mon-Fri UTC
    - cron: '0 18 * * 1-5'
  pull_request:
    branches: [ "master" ]

permissions:
    id-token: write
    contents: read

jobs:
  update_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.B2C_DEV_CREDENTIALS }}
          allow-no-subscriptions: true

      - run: |
          tenant_id=${{ secrets.B2C_TENANT_ID }}
          app_id=${{ secrets.B2C_CLIENT_ID }}
          pr_ids=$(gh pr list --json number --repo $GITHUB_REPOSITORY | jq -r '.[].number')
          echo "$pr_ids"

          # for pr_number in $pr_ids
          # do
          # az ad app update --id $app_id --web-redirect-uris \
          # https://localhost:4551/callback
          # https://pre-portal-staging.staging.platform.hmcts.net/callback
          # https://pre-portal.staging.platform.hmcts.net/callback
          # https://pre-portal-pr-${pr_id}.dev.platform.hmcts.net/callback
          # done
        env:
          REPO: ${{ github.event.repository.name }}
